### ISSUE TITLE
Error when deleting project with client and task associated

### ISSUE THREAD

**Issue by jeanhill72** [coasterboy101/Timesheet#2]
System crashes when try to delete a project after a client and task has been created

**Comment by coasterboy101** [comment]
I had a feeling that there would be issues like this. It's probably a simple database relationship issue.  It should be a simple matter of deleting all of the clients and tasks associated with the project bef

**Comment by coasterboy101** [comment]
Crap. Stupid phone.

**Comment by coasterboy101** [comment]
...Before deleting the project. (My phone decided to click the close issue button.)

**Comment by jeanhill72** [comment]
That is ok. It just needs to notify the user that there are child objects that need to be deleted first.

**Comment by coasterboy101** [comment]
It should do it automatically. Although, we should warn the user that it will be deleting more than just the project.

**Comment by coasterboy101** [comment]
Fixed.
