### ISSUE TITLE
error creating same project/clent/task entry for different day

### ISSUE THREAD

**Issue by jeanhill72** [coasterboy101/Timesheet#5]

**Comment by coasterboy101** [comment]
Are you running the updated database? I modified it last Sunday specifically because of this issue.

**Comment by jeanhill72** [comment]
What date?  Sunday as in yesterday?

**Comment by coasterboy101** [comment]
I meant the 1st.

**Comment by coasterboy101** [comment]
It looks like I will have to add an ID field to the database to fix this. It shouldn't break anything, having said that, let me know if it does. The updated database model should be on Dropbox momentarily.

**Comment by jeanhill72** [comment]
I will retry my reports after I apply the updated DB

**Comment by coasterboy101** [comment]
Sounds good. The change did fix the bug in the application, so I will mark this as closed.
